SELECT 
  car.CAR_ID,
  car.CAR_TYPE,
  FLOOR((car.DAILY_FEE - (car.DAILY_FEE * dp.DISCOUNT_RATE / 100)) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR car
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp
  ON car.CAR_TYPE = dp.CAR_TYPE
WHERE car.CAR_TYPE IN ('세단', 'SUV')
  AND dp.DURATION_TYPE = '30일 이상'
  AND car.CAR_ID NOT IN (
    SELECT rh.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY rh
    WHERE rh.START_DATE <= '2022-11-30'
      AND rh.END_DATE >= '2022-11-01'
  )
  AND FLOOR((car.DAILY_FEE - (car.DAILY_FEE * dp.DISCOUNT_RATE / 100)) * 30) >= 500000
  AND FLOOR((car.DAILY_FEE - (car.DAILY_FEE * dp.DISCOUNT_RATE / 100)) * 30) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;